"""increase_referral_code_length

Revision ID: 02f0a73ac13e
Revises: f1a2b3c4d5e8
Create Date: 2026-04-19 06:02:12.063325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02f0a73ac13e'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('referrals', 'referral_code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               nullable=False)
    # Drop default value first to avoid casting error
    op.execute('ALTER TABLE referrals ALTER COLUMN status DROP DEFAULT')
    op.alter_column('referrals', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'ACTIVE', 'INACTIVE', name='referralstatus'),
               existing_nullable=False,
               postgresql_using='status::referralstatus')
    # Re-apply the default value using the new type
    op.execute("ALTER TABLE referrals ALTER COLUMN status SET DEFAULT 'PENDING'::referralstatus")
    op.alter_column('referrals', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('referrals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_referrals_id'), 'referrals', ['id'], unique=False)
    op.drop_column('referrals', 'commission_earned')
    op.drop_column('referrals', 'commission_rate')
    op.drop_column('referrals', 'is_active')
    op.add_column('staking_positions', sa.Column('usd_value_at_staking', sa.Float(), nullable=False))
    op.alter_column('staking_positions', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'UNSTAKING', 'COMPLETED', name='stakingstatus'),
               nullable=False)
    op.create_index('idx_staking_position_active_user', 'staking_positions', ['user_id', 'is_active'], unique=False)
    # Removing redundant index and foreign key calls already in g1h2i3j4k5l6
    op.drop_column('staking_positions', 'rewards_earned')
    op.drop_column('staking_positions', 'start_date')
    op.drop_column('staking_positions', 'unlock_date')
    op.drop_column('staking_positions', 'product_id')
    op.add_column('staking_products', sa.Column('created_by_admin_id', sa.String(36), nullable=True))
    op.create_index('idx_staking_product_type_active', 'staking_products', ['staking_type', 'is_active'], unique=False)
    op.create_foreign_key('fk_staking_products_admin_id', 'staking_products', 'admins', ['created_by_admin_id'], ['id'])
    op.drop_column('staking_products', 'is_flexible')
    op.drop_column('staking_products', 'min_amount')
    op.drop_column('staking_products', 'apy')
    op.alter_column('users', 'referral_code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('users', 'referral_tier',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'referral_tier',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('users', 'referral_code',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.add_column('staking_products', sa.Column('apy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('staking_products', sa.Column('min_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('staking_products', sa.Column('is_flexible', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_staking_products_admin_id', 'staking_products', type_='foreignkey')
    op.drop_index('idx_staking_product_type_active', table_name='staking_products')
    op.drop_column('staking_products', 'created_by_admin_id')
    op.add_column('staking_positions', sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('staking_positions', sa.Column('unlock_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('staking_positions', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('staking_positions', sa.Column('rewards_earned', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index('idx_staking_position_active_user', table_name='staking_positions')
    op.alter_column('staking_positions', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'UNSTAKING', 'COMPLETED', name='stakingstatus'),
               nullable=True)
    op.drop_column('staking_positions', 'usd_value_at_staking')
    op.add_column('referrals', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('referrals', sa.Column('commission_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('referrals', sa.Column('commission_earned', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_referrals_id'), table_name='referrals')
    op.alter_column('referrals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('referrals', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('referrals', 'status',
               existing_type=sa.Enum('PENDING', 'ACTIVE', 'INACTIVE', name='referralstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.alter_column('referrals', 'referral_code',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
