"""add_signals_system

Revision ID: 04af1d8ef041
Revises: f1a2b3c4d5e6
Create Date: 2026-03-29 10:57:52.333509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04af1d8ef041'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal_generic_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_generic_cache_cache_key'), 'signal_generic_cache', ['cache_key'], unique=True)
    op.create_index(op.f('ix_signal_generic_cache_expires_at'), 'signal_generic_cache', ['expires_at'], unique=False)

    op.create_index(op.f('ix_deposit_addresses_id'), 'deposit_addresses', ['id'], unique=False)
    op.add_column('signal_history', sa.Column('exit_price', sa.Numeric(precision=20, scale=10), nullable=True))
    op.add_column('signal_history', sa.Column('result_percent', sa.Numeric(precision=10, scale=4), nullable=True))
    op.drop_column('signal_history', 'profit_pct')
    op.drop_column('signal_history', 'close_price')
    op.add_column('signals', sa.Column('asset_type', sa.Enum('CRYPTO', 'FOREX', 'STOCKS', name='assettype'), nullable=True))
    op.add_column('signals', sa.Column('strength', sa.Enum('STRONG', 'MODERATE', 'WEAK', name='signalstrength'), nullable=True))
    op.add_column('signals', sa.Column('timeframe', sa.String(), nullable=True))
    op.add_column('signals', sa.Column('take_profit', sa.Numeric(precision=20, scale=10), nullable=True))
    op.add_column('signals', sa.Column('rsi', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('signals', sa.Column('macd', sa.String(), nullable=True))
    op.add_column('signals', sa.Column('ema_signal', sa.String(), nullable=True))
    op.add_column('signals', sa.Column('bb_signal', sa.String(), nullable=True))
    op.add_column('signals', sa.Column('sma_signal', sa.String(), nullable=True))
    op.add_column('signals', sa.Column('indicators_raw', sa.JSON(), nullable=True))
    op.add_column('signals', sa.Column('generated_at', sa.DateTime(), nullable=True))
    op.add_column('signals', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('signals', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('signals', 'symbol',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('signals', 'signal_type',
               existing_type=postgresql.ENUM('BUY', 'SELL', 'HOLD', name='signaltype'),
               nullable=True)
    op.alter_column('signals', 'entry_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('signals', 'stop_loss',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=10),
               existing_nullable=True)
    op.create_index(op.f('ix_signals_asset_type'), 'signals', ['asset_type'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.drop_constraint(op.f('signals_analyst_id_fkey'), 'signals', type_='foreignkey')
    op.drop_column('signals', 'target_price')
    op.drop_column('signals', 'analyst_id')
    op.drop_column('signals', 'analysis')
    op.drop_column('signals', 'confidence')
    op.create_index(op.f('ix_withdrawals_confirmation_token'), 'withdrawals', ['confirmation_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_withdrawals_confirmation_token'), table_name='withdrawals')
    op.add_column('signals', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('signals', sa.Column('analysis', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('signals', sa.Column('analyst_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('signals', sa.Column('target_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('signals_analyst_id_fkey'), 'signals', 'users', ['analyst_id'], ['id'])
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index(op.f('ix_signals_asset_type'), table_name='signals')
    op.alter_column('signals', 'stop_loss',
               existing_type=sa.Numeric(precision=20, scale=10),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('signals', 'entry_price',
               existing_type=sa.Numeric(precision=20, scale=10),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('signals', 'signal_type',
               existing_type=postgresql.ENUM('BUY', 'SELL', 'HOLD', name='signaltype'),
               nullable=False)
    op.alter_column('signals', 'symbol',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('signals', 'is_active')
    op.drop_column('signals', 'expires_at')
    op.drop_column('signals', 'generated_at')
    op.drop_column('signals', 'indicators_raw')
    op.drop_column('signals', 'sma_signal')
    op.drop_column('signals', 'bb_signal')
    op.drop_column('signals', 'ema_signal')
    op.drop_column('signals', 'macd')
    op.drop_column('signals', 'rsi')
    op.drop_column('signals', 'take_profit')
    op.drop_column('signals', 'timeframe')
    op.drop_column('signals', 'strength')
    op.drop_column('signals', 'asset_type')
    op.add_column('signal_history', sa.Column('close_price', sa.NUMERIC(precision=20, scale=10), autoincrement=False, nullable=True))
    op.add_column('signal_history', sa.Column('profit_pct', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True))
    op.drop_column('signal_history', 'result_percent')
    op.drop_column('signal_history', 'exit_price')

    op.drop_index(op.f('ix_signal_generic_cache_expires_at'), table_name='signal_generic_cache')
    op.drop_index(op.f('ix_signal_generic_cache_cache_key'), table_name='signal_generic_cache')
    op.drop_table('signal_generic_cache')
    # ### end Alembic commands ###
