"""add_signals_system

Revision ID: 04af1d8ef041
Revises: f1a2b3c4d5e6
Create Date: 2026-03-29 10:57:52.333509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04af1d8ef041'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal_generic_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_generic_cache_cache_key'), 'signal_generic_cache', ['cache_key'], unique=True)
    op.create_index(op.f('ix_signal_generic_cache_expires_at'), 'signal_generic_cache', ['expires_at'], unique=False)
    op.drop_index(op.f('ix_signal_indicator_cache_symbol'), table_name='signal_indicator_cache')
    op.drop_table('signal_indicator_cache')
    op.drop_index(op.f('ix_copy_trade_history_copy_trading_id'), table_name='copy_trade_history')
    op.drop_table('copy_trade_history')
    op.drop_index(op.f('ix_trading_signals_id'), table_name='trading_signals')
    op.drop_index(op.f('ix_trading_signals_source_id'), table_name='trading_signals')
    op.drop_index(op.f('ix_trading_signals_symbol'), table_name='trading_signals')
    op.drop_table('trading_signals')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')
    op.drop_index(op.f('ix_copy_trading_bitget_copy_id'), table_name='copy_trading')
    op.drop_index(op.f('ix_copy_trading_user_id'), table_name='copy_trading')
    op.drop_table('copy_trading')
    op.drop_index(op.f('ix_signal_sources_id'), table_name='signal_sources')
    op.drop_table('signal_sources')
    op.create_index(op.f('ix_deposit_addresses_id'), 'deposit_addresses', ['id'], unique=False)
    op.add_column('signal_history', sa.Column('exit_price', sa.Numeric(precision=20, scale=10), nullable=True))
    op.add_column('signal_history', sa.Column('result_percent', sa.Numeric(precision=10, scale=4), nullable=True))
    op.drop_column('signal_history', 'profit_pct')
    op.drop_column('signal_history', 'close_price')
    op.add_column('signals', sa.Column('asset_type', sa.Enum('CRYPTO', 'FOREX', 'STOCKS', name='assettype'), nullable=True))
    op.add_column('signals', sa.Column('strength', sa.Enum('STRONG', 'MODERATE', 'WEAK', name='signalstrength'), nullable=True))
    op.add_column('signals', sa.Column('timeframe', sa.String(), nullable=True))
    op.add_column('signals', sa.Column('take_profit', sa.Numeric(precision=20, scale=10), nullable=True))
    op.add_column('signals', sa.Column('rsi', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('signals', sa.Column('macd', sa.String(), nullable=True))
    op.add_column('signals', sa.Column('ema_signal', sa.String(), nullable=True))
    op.add_column('signals', sa.Column('bb_signal', sa.String(), nullable=True))
    op.add_column('signals', sa.Column('sma_signal', sa.String(), nullable=True))
    op.add_column('signals', sa.Column('indicators_raw', sa.JSON(), nullable=True))
    op.add_column('signals', sa.Column('generated_at', sa.DateTime(), nullable=True))
    op.add_column('signals', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('signals', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('signals', 'symbol',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('signals', 'signal_type',
               existing_type=postgresql.ENUM('BUY', 'SELL', 'HOLD', name='signaltype'),
               nullable=True)
    op.alter_column('signals', 'entry_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('signals', 'stop_loss',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=10),
               existing_nullable=True)
    op.create_index(op.f('ix_signals_asset_type'), 'signals', ['asset_type'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.drop_constraint(op.f('signals_analyst_id_fkey'), 'signals', type_='foreignkey')
    op.drop_column('signals', 'target_price')
    op.drop_column('signals', 'analyst_id')
    op.drop_column('signals', 'analysis')
    op.drop_column('signals', 'confidence')
    op.create_index(op.f('ix_withdrawals_confirmation_token'), 'withdrawals', ['confirmation_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_withdrawals_confirmation_token'), table_name='withdrawals')
    op.add_column('signals', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('signals', sa.Column('analysis', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('signals', sa.Column('analyst_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('signals', sa.Column('target_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('signals_analyst_id_fkey'), 'signals', 'users', ['analyst_id'], ['id'])
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index(op.f('ix_signals_asset_type'), table_name='signals')
    op.alter_column('signals', 'stop_loss',
               existing_type=sa.Numeric(precision=20, scale=10),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('signals', 'entry_price',
               existing_type=sa.Numeric(precision=20, scale=10),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('signals', 'signal_type',
               existing_type=postgresql.ENUM('BUY', 'SELL', 'HOLD', name='signaltype'),
               nullable=False)
    op.alter_column('signals', 'symbol',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('signals', 'is_active')
    op.drop_column('signals', 'expires_at')
    op.drop_column('signals', 'generated_at')
    op.drop_column('signals', 'indicators_raw')
    op.drop_column('signals', 'sma_signal')
    op.drop_column('signals', 'bb_signal')
    op.drop_column('signals', 'ema_signal')
    op.drop_column('signals', 'macd')
    op.drop_column('signals', 'rsi')
    op.drop_column('signals', 'take_profit')
    op.drop_column('signals', 'timeframe')
    op.drop_column('signals', 'strength')
    op.drop_column('signals', 'asset_type')
    op.add_column('signal_history', sa.Column('close_price', sa.NUMERIC(precision=20, scale=10), autoincrement=False, nullable=True))
    op.add_column('signal_history', sa.Column('profit_pct', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True))
    op.drop_column('signal_history', 'result_percent')
    op.drop_column('signal_history', 'exit_price')
    op.drop_index(op.f('ix_deposit_addresses_id'), table_name='deposit_addresses')
    op.create_table('signal_sources',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('accuracy_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_trades', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('signal_sources_pkey'))
    )
    op.create_index(op.f('ix_signal_sources_id'), 'signal_sources', ['id'], unique=False)
    op.create_table('copy_trading',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('bitget_copy_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('bitget_trader_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('trader_username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('copy_mode', postgresql.ENUM('PROPORTIONAL', 'FIXED_AMOUNT', 'PERCENTAGE', name='copymodeenum'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'PAUSED', 'STOPPED', name='copystatus'), autoincrement=False, nullable=False),
    sa.Column('leverage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fixed_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_position_size', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('stop_loss_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('stop_loss_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('take_profit_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('take_profit_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_daily_copy_trades', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('auto_stop_on_loss', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('auto_stop_loss_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_copied_trades', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_pnl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_pnl_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('win_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('loss_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cumulative_loss', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('daily_trades_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('stopped_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('copy_trading_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('copy_trading_pkey'))
    )
    op.create_index(op.f('ix_copy_trading_user_id'), 'copy_trading', ['user_id'], unique=False)
    op.create_index(op.f('ix_copy_trading_bitget_copy_id'), 'copy_trading', ['bitget_copy_id'], unique=True)
    op.create_table('admins',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'DISABLED', name='adminstatus'), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('admins_pkey'))
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_table('trading_signals',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('action', postgresql.ENUM('BUY', 'SELL', name='signalaction'), autoincrement=False, nullable=False),
    sa.Column('entry_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('target_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('stop_loss', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('trading_signals_pkey'))
    )
    op.create_index(op.f('ix_trading_signals_symbol'), 'trading_signals', ['symbol'], unique=False)
    op.create_index(op.f('ix_trading_signals_source_id'), 'trading_signals', ['source_id'], unique=False)
    op.create_index(op.f('ix_trading_signals_id'), 'trading_signals', ['id'], unique=False)
    op.create_table('copy_trade_history',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('copy_trading_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('bitget_trade_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('side', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('entry_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('exit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pnl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pnl_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('opened_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('closed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['copy_trading_id'], ['copy_trading.id'], name=op.f('copy_trade_history_copy_trading_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('copy_trade_history_pkey')),
    sa.UniqueConstraint('bitget_trade_id', name=op.f('copy_trade_history_bitget_trade_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_copy_trade_history_copy_trading_id'), 'copy_trade_history', ['copy_trading_id'], unique=False)
    op.create_table('signal_indicator_cache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('indicator_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('signal_indicator_cache_pkey'))
    )
    op.create_index(op.f('ix_signal_indicator_cache_symbol'), 'signal_indicator_cache', ['symbol'], unique=False)
    op.drop_index(op.f('ix_signal_generic_cache_expires_at'), table_name='signal_generic_cache')
    op.drop_index(op.f('ix_signal_generic_cache_cache_key'), table_name='signal_generic_cache')
    op.drop_table('signal_generic_cache')
    # ### end Alembic commands ###
