"""initial_master_migration

Revision ID: 19a7bae933bf
Revises: 
Create Date: 2026-05-01 14:18:04.200571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19a7bae933bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='adminstatus'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('coingecko_id', sa.String(length=100), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('market_cap_rank', sa.Float(), nullable=True),
    sa.Column('total_volume', sa.Float(), nullable=True),
    sa.Column('high_24h', sa.Float(), nullable=True),
    sa.Column('low_24h', sa.Float(), nullable=True),
    sa.Column('price_change_24h', sa.Float(), nullable=True),
    sa.Column('price_change_percentage_24h', sa.Float(), nullable=True),
    sa.Column('circulating_supply', sa.Float(), nullable=True),
    sa.Column('total_supply', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coingecko_id')
    )
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=True)
    op.create_table('cold_storage_vaults',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('asset_symbol', sa.String(length=10), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('last_withdrawal_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cold_storage_vaults_id'), 'cold_storage_vaults', ['id'], unique=False)
    op.create_index(op.f('ix_cold_storage_vaults_user_id'), 'cold_storage_vaults', ['user_id'], unique=True)
    op.create_table('copy_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('trader_id', sa.String(length=36), nullable=False),
    sa.Column('allocation_amount', sa.Float(), nullable=False),
    sa.Column('current_pnl', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copy_sessions_id'), 'copy_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_copy_sessions_user_id'), 'copy_sessions', ['user_id'], unique=False)
    op.create_table('copy_traders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('total_pnl_percent', sa.Float(), nullable=True),
    sa.Column('avg_trade_duration', sa.String(length=50), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('performance_data', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_copy_traders_id'), 'copy_traders', ['id'], unique=False)
    op.create_table('deposit_addresses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset', sa.String(length=10), nullable=False),
    sa.Column('network', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('qr_code_url', sa.String(length=512), nullable=False),
    sa.Column('min_deposit', sa.Float(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset', 'network', name='uq_deposit_addresses_asset_network')
    )
    op.create_index(op.f('ix_deposit_addresses_asset'), 'deposit_addresses', ['asset'], unique=False)
    op.create_index(op.f('ix_deposit_addresses_id'), 'deposit_addresses', ['id'], unique=False)
    op.create_index(op.f('ix_deposit_addresses_network'), 'deposit_addresses', ['network'], unique=False)
    op.create_table('deposits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('asset_symbol', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('fiat_amount', sa.Float(), nullable=True),
    sa.Column('wallet_address', sa.String(length=255), nullable=True),
    sa.Column('blockchain_network', sa.String(length=50), nullable=True),
    sa.Column('transaction_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'REJECTED', 'EXPIRED', name='depositstatus'), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_hash')
    )
    op.create_index(op.f('ix_deposits_id'), 'deposits', ['id'], unique=False)
    op.create_index(op.f('ix_deposits_user_id'), 'deposits', ['user_id'], unique=False)
    op.create_table('execution_trades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=True),
    sa.Column('fee_asset', sa.String(length=10), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_trades_id'), 'execution_trades', ['id'], unique=False)
    op.create_index(op.f('ix_execution_trades_order_id'), 'execution_trades', ['order_id'], unique=False)
    op.create_index(op.f('ix_execution_trades_user_id'), 'execution_trades', ['user_id'], unique=False)
    op.create_table('investment_positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('apy_at_start', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'MATURED', 'REDEEMED', 'CLOSED', name='investmentstatus'), nullable=True),
    sa.Column('total_earnings', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('maturity_date', sa.DateTime(), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_positions_id'), 'investment_positions', ['id'], unique=False)
    op.create_index(op.f('ix_investment_positions_user_id'), 'investment_positions', ['user_id'], unique=False)
    op.create_table('investment_products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('FIXED', 'FLEXIBLE', 'STAKING', 'MINING', 'REAL_ESTATE', name='investmenttype'), nullable=False),
    sa.Column('asset_symbol', sa.String(length=10), nullable=False),
    sa.Column('apy', sa.Float(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('min_investment', sa.Float(), nullable=True),
    sa.Column('max_investment', sa.Float(), nullable=True),
    sa.Column('total_staked', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_products_id'), 'investment_products', ['id'], unique=False)
    op.create_table('mining_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('coin_symbol', sa.String(length=20), nullable=False),
    sa.Column('hashrate', sa.String(length=50), nullable=False),
    sa.Column('daily_earnings', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('duration_days', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mining_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('coin_symbol', sa.String(length=20), nullable=False),
    sa.Column('network_hashrate', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('next_difficulty_est', sa.String(length=50), nullable=True),
    sa.Column('block_time_avg', sa.Float(), nullable=True),
    sa.Column('daily_revenue_per_hash', sa.Float(), nullable=True),
    sa.Column('active_miners_count', sa.Float(), nullable=True),
    sa.Column('total_platform_hashrate', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coin_symbol'),
    sa.UniqueConstraint('coin_symbol', name='uq_mining_stats_coin_symbol')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('type', sa.Enum('MARKET', 'LIMIT', 'STOP_LOSS', 'TAKE_PROFIT', name='ordertype'), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'OPEN', 'FILLED', 'PARTIALLY_FILLED', 'CANCELLED', 'EXPIRED', 'REJECTED', name='orderstatus'), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('executed_quantity', sa.Float(), nullable=True),
    sa.Column('average_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('price_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=False),
    sa.Column('condition', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_triggered', sa.Boolean(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_alerts_id'), 'price_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_price_alerts_user_id'), 'price_alerts', ['user_id'], unique=False)
    op.create_table('real_estate_cache',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cache_key', sa.String(length=255), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_real_estate_cache_cache_key'), 'real_estate_cache', ['cache_key'], unique=True)
    op.create_table('real_estate_properties',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('annual_roi', sa.Float(), nullable=False),
    sa.Column('tokens_issued', sa.Float(), nullable=False),
    sa.Column('tokens_available', sa.Float(), nullable=False),
    sa.Column('min_investment', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_accuracy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('asset_type', sa.Enum('CRYPTO', 'FOREX', 'STOCKS', name='assettype'), nullable=True),
    sa.Column('signal_type', sa.Enum('BUY', 'SELL', name='signaltype'), nullable=True),
    sa.Column('total_signals', sa.Integer(), nullable=True),
    sa.Column('winning_signals', sa.Integer(), nullable=True),
    sa.Column('accuracy_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('last_calculated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_accuracy_symbol'), 'signal_accuracy', ['symbol'], unique=False)
    op.create_table('signal_generic_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_generic_cache_cache_key'), 'signal_generic_cache', ['cache_key'], unique=True)
    op.create_index(op.f('ix_signal_generic_cache_expires_at'), 'signal_generic_cache', ['expires_at'], unique=False)
    op.create_table('signal_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('asset_type', sa.Enum('CRYPTO', 'FOREX', 'STOCKS', name='assettype'), nullable=True),
    sa.Column('signal_type', sa.Enum('BUY', 'SELL', name='signaltype'), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('outcome', sa.Enum('PENDING', 'WIN', 'LOSS', 'EXPIRED', name='signaloutcome'), nullable=True),
    sa.Column('result_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('timeframe', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_history_signal_id'), 'signal_history', ['signal_id'], unique=False)
    op.create_index(op.f('ix_signal_history_symbol'), 'signal_history', ['symbol'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('asset_type', sa.Enum('CRYPTO', 'FOREX', 'STOCKS', name='assettype'), nullable=True),
    sa.Column('signal_type', sa.Enum('BUY', 'SELL', name='signaltype'), nullable=True),
    sa.Column('strength', sa.Enum('STRONG', 'MODERATE', 'WEAK', name='signalstrength'), nullable=True),
    sa.Column('timeframe', sa.String(), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('rsi', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('macd', sa.String(), nullable=True),
    sa.Column('ema_signal', sa.String(), nullable=True),
    sa.Column('bb_signal', sa.String(), nullable=True),
    sa.Column('sma_signal', sa.String(), nullable=True),
    sa.Column('indicators_raw', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_asset_type'), 'signals', ['asset_type'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.Enum('BASIC', 'PRO', 'ELITE', 'PRIME_MASTER', name='usertier'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.create_table('support_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_messages_id'), 'support_messages', ['id'], unique=False)
    op.create_index(op.f('ix_support_messages_ticket_id'), 'support_messages', ['ticket_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='ticketstatus'), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_id'), 'support_tickets', ['id'], unique=False)
    op.create_index(op.f('ix_support_tickets_user_id'), 'support_tickets', ['user_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=1000), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('trading_pairs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('base_asset', sa.String(length=10), nullable=False),
    sa.Column('quote_asset', sa.String(length=10), nullable=False),
    sa.Column('binance_symbol', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('min_order_qty', sa.Float(), nullable=True),
    sa.Column('max_order_qty', sa.Float(), nullable=True),
    sa.Column('price_precision', sa.Integer(), nullable=True),
    sa.Column('qty_precision', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_pairs_id'), 'trading_pairs', ['id'], unique=False)
    op.create_index(op.f('ix_trading_pairs_symbol'), 'trading_pairs', ['symbol'], unique=True)
    op.create_table('user_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('asset_symbol', sa.String(length=10), nullable=False),
    sa.Column('total_balance', sa.Float(), nullable=True),
    sa.Column('available_balance', sa.Float(), nullable=True),
    sa.Column('locked_balance', sa.Float(), nullable=True),
    sa.Column('average_buy_price', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_assets_asset_symbol'), 'user_assets', ['asset_symbol'], unique=False)
    op.create_index(op.f('ix_user_assets_id'), 'user_assets', ['id'], unique=False)
    op.create_index(op.f('ix_user_assets_user_id'), 'user_assets', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('account_type', sa.Enum('INDIVIDUAL', 'JOINT', 'CORPORATE', name='accounttype'), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verification_token', sa.String(length=100), nullable=True),
    sa.Column('email_verification_expires_at', sa.DateTime(), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=True),
    sa.Column('two_factor_secret', sa.String(length=100), nullable=True),
    sa.Column('backup_codes', sa.Text(), nullable=True),
    sa.Column('profile_picture_url', sa.String(length=500), nullable=True),
    sa.Column('tier', sa.Enum('BASIC', 'PRO', 'ELITE', 'PRIME_MASTER', name='usertier'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'PENDING_VERIFICATION', name='userstatus'), nullable=True),
    sa.Column('kyc_status', sa.Enum('UNVERIFIED', 'PENDING', 'VERIFIED', 'REJECTED', name='kycstatus'), nullable=True),
    sa.Column('kyc_rejection_reason', sa.Text(), nullable=True),
    sa.Column('account_balance', sa.Float(), nullable=True),
    sa.Column('trading_balance', sa.Float(), nullable=True),
    sa.Column('cold_storage_balance', sa.Float(), nullable=True),
    sa.Column('referral_code', sa.String(length=100), nullable=True),
    sa.Column('referred_by', sa.String(length=36), nullable=True),
    sa.Column('referral_earnings', sa.Float(), nullable=True),
    sa.Column('referral_tier', sa.Integer(), nullable=True),
    sa.Column('copy_trading_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('withdrawals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('asset_symbol', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=True),
    sa.Column('net_amount', sa.Float(), nullable=False),
    sa.Column('destination_address', sa.String(length=255), nullable=False),
    sa.Column('blockchain_network', sa.String(length=50), nullable=True),
    sa.Column('transaction_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING_2FA', 'AWAITING_CONFIRMATION', 'PENDING_APPROVAL', 'PROCESSING', 'COMPLETED', 'REJECTED', 'CANCELLED', name='withdrawalstatus'), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('confirmation_token', sa.String(length=255), nullable=True),
    sa.Column('confirmation_expires_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_hash')
    )
    op.create_index(op.f('ix_withdrawals_confirmation_token'), 'withdrawals', ['confirmation_token'], unique=False)
    op.create_index(op.f('ix_withdrawals_id'), 'withdrawals', ['id'], unique=False)
    op.create_index(op.f('ix_withdrawals_user_id'), 'withdrawals', ['user_id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('account_type', sa.Enum('TRADING', 'SAVINGS', 'INVESTMENT', 'MINING', name='accounttype'), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('copied_signals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('signal_id', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('signal_type', sa.Enum('BUY', 'SELL', name='signaltype'), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', 'CANCELLED', name='copystatus'), nullable=True),
    sa.Column('copied_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copied_signals_user_id'), 'copied_signals', ['user_id'], unique=False)
    op.create_table('copy_trading',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('bitget_copy_id', sa.String(length=255), nullable=False),
    sa.Column('bitget_trader_id', sa.String(length=255), nullable=False),
    sa.Column('trader_username', sa.String(length=255), nullable=False),
    sa.Column('copy_mode', sa.Enum('PROPORTIONAL', 'FIXED_AMOUNT', 'PERCENTAGE', name='copymodeenum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'STOPPED', name='copystatus'), nullable=False),
    sa.Column('leverage', sa.Float(), nullable=True),
    sa.Column('fixed_amount', sa.Float(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('max_position_size', sa.Float(), nullable=True),
    sa.Column('stop_loss_enabled', sa.Boolean(), nullable=True),
    sa.Column('stop_loss_percentage', sa.Float(), nullable=True),
    sa.Column('take_profit_enabled', sa.Boolean(), nullable=True),
    sa.Column('take_profit_percentage', sa.Float(), nullable=True),
    sa.Column('max_daily_copy_trades', sa.Integer(), nullable=True),
    sa.Column('auto_stop_on_loss', sa.Boolean(), nullable=True),
    sa.Column('auto_stop_loss_threshold', sa.Float(), nullable=True),
    sa.Column('total_copied_trades', sa.Integer(), nullable=True),
    sa.Column('total_pnl', sa.Float(), nullable=True),
    sa.Column('total_pnl_percentage', sa.Float(), nullable=True),
    sa.Column('win_count', sa.Integer(), nullable=True),
    sa.Column('loss_count', sa.Integer(), nullable=True),
    sa.Column('cumulative_loss', sa.Float(), nullable=True),
    sa.Column('daily_trades_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copy_trading_bitget_copy_id'), 'copy_trading', ['bitget_copy_id'], unique=True)
    op.create_index(op.f('ix_copy_trading_user_id'), 'copy_trading', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('document_type', sa.Enum('PASSPORT', 'ID_CARD', 'DRIVERS_LICENSE', 'PROOF_OF_ADDRESS', 'BANK_STATEMENT', 'BUSINESS_LICENSE', 'ARTICLES_OF_ASSOCIATION', 'JOINT_OWNERSHIP_AGREEMENT', name='documenttype'), nullable=False),
    sa.Column('cloudinary_url', sa.String(length=500), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.String(length=20), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('login_timestamp', sa.DateTime(), nullable=True),
    sa.Column('logout_timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_suspicious', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mining_subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED', name='miningstatus'), nullable=True),
    sa.Column('total_earnings', sa.Float(), nullable=True),
    sa.Column('last_paid_at', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['mining_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('real_estate_investments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('external_property_id', sa.String(length=100), nullable=False),
    sa.Column('property_snapshot', sa.JSON(), nullable=False),
    sa.Column('tokens_owned', sa.Integer(), nullable=True),
    sa.Column('amount_invested', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('monthly_income', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('roi_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PENDING', 'EXITED', name='investmentstatus'), nullable=True),
    sa.Column('invested_at', sa.DateTime(), nullable=True),
    sa.Column('exited_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_real_estate_investments_user_id'), 'real_estate_investments', ['user_id'], unique=False)
    op.create_table('real_estate_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('external_property_id', sa.String(length=100), nullable=False),
    sa.Column('property_title', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('FRACTIONAL_INVESTMENT', 'DIVIDEND', 'EXIT', name='realestatetransactiontype'), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='transactionstatus'), nullable=True),
    sa.Column('payment_source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_real_estate_transactions_user_id'), 'real_estate_transactions', ['user_id'], unique=False)
    op.create_table('referral_payouts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('referrer_id', sa.String(length=36), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('commission_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='payoutstatus'), nullable=False),
    sa.Column('payout_date', sa.Date(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referrer_id', 'payout_date', name='uq_referral_payout_user_date')
    )
    op.create_index(op.f('ix_referral_payouts_id'), 'referral_payouts', ['id'], unique=False)
    op.create_index(op.f('ix_referral_payouts_referrer_id'), 'referral_payouts', ['referrer_id'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('referrer_id', sa.String(length=36), nullable=False),
    sa.Column('referred_id', sa.String(length=36), nullable=False),
    sa.Column('referral_code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'INACTIVE', name='referralstatus'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['referred_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_id'), 'referrals', ['id'], unique=False)
    op.create_index(op.f('ix_referrals_referral_code'), 'referrals', ['referral_code'], unique=False)
    op.create_index(op.f('ix_referrals_referred_id'), 'referrals', ['referred_id'], unique=True)
    op.create_index(op.f('ix_referrals_referrer_id'), 'referrals', ['referrer_id'], unique=False)
    op.create_table('staking_products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asset_symbol', sa.String(length=20), nullable=False),
    sa.Column('staking_type', sa.Enum('FLEXIBLE', 'FIXED_30', 'FIXED_90', 'FIXED_180', name='stakingtype'), nullable=False),
    sa.Column('annual_percentage_yield', sa.Float(), nullable=False),
    sa.Column('min_stake_amount', sa.Float(), nullable=False),
    sa.Column('lock_period_days', sa.Integer(), nullable=True),
    sa.Column('payout_frequency', sa.Enum('DAILY', 'MONTHLY', 'END_OF_TERM', name='payoutfrequency'), nullable=False),
    sa.Column('pool_capacity_amount', sa.Float(), nullable=True),
    sa.Column('current_total_staked', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by_admin_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_staking_product_asset', 'staking_products', ['asset_symbol'], unique=False)
    op.create_index('idx_staking_product_type_active', 'staking_products', ['staking_type', 'is_active'], unique=False)
    op.create_index(op.f('ix_staking_products_asset_symbol'), 'staking_products', ['asset_symbol'], unique=False)
    op.create_index(op.f('ix_staking_products_is_active'), 'staking_products', ['is_active'], unique=False)
    op.create_index(op.f('ix_staking_products_staking_type'), 'staking_products', ['staking_type'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('trade_type', sa.Enum('BUY', 'SELL', name='tradetype'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'FILLED', 'PARTIAL', 'CANCELLED', 'REJECTED', name='tradestatus'), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_percentage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('payment_proof', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_subscriptions_id'), 'user_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_user_id'), 'user_subscriptions', ['user_id'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('wallet_type', sa.Enum('CRYPTO', 'FIAT', 'COLD_STORAGE', name='wallettype'), nullable=False),
    sa.Column('asset_symbol', sa.String(length=20), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('address_normalized', sa.String(length=500), nullable=True),
    sa.Column('qr_code_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'address_normalized', name='uq_wallet_user_address_normalized')
    )
    op.create_index(op.f('ix_wallets_address_normalized'), 'wallets', ['address_normalized'], unique=False)
    op.create_table('copy_trade_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('copy_trading_id', sa.String(length=36), nullable=False),
    sa.Column('bitget_trade_id', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_percentage', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['copy_trading_id'], ['copy_trading.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bitget_trade_id')
    )
    op.create_index(op.f('ix_copy_trade_history_copy_trading_id'), 'copy_trade_history', ['copy_trading_id'], unique=False)
    op.create_table('referral_commissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('referrer_id', sa.String(length=36), nullable=False),
    sa.Column('referred_id', sa.String(length=36), nullable=False),
    sa.Column('referral_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.Enum('TRADE', 'DEPOSIT', name='commissionsourcetype'), nullable=False),
    sa.Column('source_amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'CANCELLED', name='commissionstatus'), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ),
    sa.ForeignKeyConstraint(['referred_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_commissions_id'), 'referral_commissions', ['id'], unique=False)
    op.create_index(op.f('ix_referral_commissions_referral_id'), 'referral_commissions', ['referral_id'], unique=False)
    op.create_index(op.f('ix_referral_commissions_referred_id'), 'referral_commissions', ['referred_id'], unique=False)
    op.create_index(op.f('ix_referral_commissions_referrer_id'), 'referral_commissions', ['referrer_id'], unique=False)
    op.create_table('staking_positions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('pool_id', sa.String(), nullable=False),
    sa.Column('amount_staked', sa.Float(), nullable=False),
    sa.Column('usd_value_at_staking', sa.Float(), nullable=False),
    sa.Column('total_earned_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', name='stakingstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('earned_until_date', sa.DateTime(), nullable=True),
    sa.Column('last_payout_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pool_id'], ['staking_products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_staking_position_active_user', 'staking_positions', ['user_id', 'is_active'], unique=False)
    op.create_index('idx_staking_position_pool', 'staking_positions', ['pool_id'], unique=False)
    op.create_index(op.f('ix_staking_positions_is_active'), 'staking_positions', ['is_active'], unique=False)
    op.create_index(op.f('ix_staking_positions_pool_id'), 'staking_positions', ['pool_id'], unique=False)
    op.create_index(op.f('ix_staking_positions_user_id'), 'staking_positions', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.Enum('DEPOSIT', 'WITHDRAWAL', 'TRADE', 'STAKING_DEPOSIT', 'STAKING_WITHDRAWAL', 'STAKING_REWARD', 'MINING_REWARD', 'INVESTMENT_RETURN', 'REFERRAL_COMMISSION', 'SUBSCRIPTION_PAYMENT', 'SUBSCRIPTION_REQUEST', 'COLD_STORAGE_DEPOSIT', 'COLD_STORAGE_WITHDRAWAL', name='transactiontype'), nullable=False),
    sa.Column('asset_symbol', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('usd_amount', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('staking_rewards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('position_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('earned_on_date', sa.DateTime(), nullable=False),
    sa.Column('paid_on_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACCRUED', 'PAID', 'CLAIMED', name='rewardstatus'), nullable=False),
    sa.Column('reward_type', sa.Enum('DAILY_ACCRUAL', 'MONTHLY_PAYOUT', 'TERM_END', name='rewardtype'), nullable=False),
    sa.Column('usd_amount_at_payout', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['staking_positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_staking_reward_position_status', 'staking_rewards', ['position_id', 'status'], unique=False)
    op.create_index(op.f('ix_staking_rewards_earned_on_date'), 'staking_rewards', ['earned_on_date'], unique=False)
    op.create_index(op.f('ix_staking_rewards_position_id'), 'staking_rewards', ['position_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staking_rewards_position_id'), table_name='staking_rewards')
    op.drop_index(op.f('ix_staking_rewards_earned_on_date'), table_name='staking_rewards')
    op.drop_index('idx_staking_reward_position_status', table_name='staking_rewards')
    op.drop_table('staking_rewards')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_staking_positions_user_id'), table_name='staking_positions')
    op.drop_index(op.f('ix_staking_positions_pool_id'), table_name='staking_positions')
    op.drop_index(op.f('ix_staking_positions_is_active'), table_name='staking_positions')
    op.drop_index('idx_staking_position_pool', table_name='staking_positions')
    op.drop_index('idx_staking_position_active_user', table_name='staking_positions')
    op.drop_table('staking_positions')
    op.drop_index(op.f('ix_referral_commissions_referrer_id'), table_name='referral_commissions')
    op.drop_index(op.f('ix_referral_commissions_referred_id'), table_name='referral_commissions')
    op.drop_index(op.f('ix_referral_commissions_referral_id'), table_name='referral_commissions')
    op.drop_index(op.f('ix_referral_commissions_id'), table_name='referral_commissions')
    op.drop_table('referral_commissions')
    op.drop_index(op.f('ix_copy_trade_history_copy_trading_id'), table_name='copy_trade_history')
    op.drop_table('copy_trade_history')
    op.drop_index(op.f('ix_wallets_address_normalized'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_user_subscriptions_user_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_id'), table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_table('trades')
    op.drop_index(op.f('ix_staking_products_staking_type'), table_name='staking_products')
    op.drop_index(op.f('ix_staking_products_is_active'), table_name='staking_products')
    op.drop_index(op.f('ix_staking_products_asset_symbol'), table_name='staking_products')
    op.drop_index('idx_staking_product_type_active', table_name='staking_products')
    op.drop_index('idx_staking_product_asset', table_name='staking_products')
    op.drop_table('staking_products')
    op.drop_index(op.f('ix_referrals_referrer_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referred_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referral_code'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_referral_payouts_referrer_id'), table_name='referral_payouts')
    op.drop_index(op.f('ix_referral_payouts_id'), table_name='referral_payouts')
    op.drop_table('referral_payouts')
    op.drop_index(op.f('ix_real_estate_transactions_user_id'), table_name='real_estate_transactions')
    op.drop_table('real_estate_transactions')
    op.drop_index(op.f('ix_real_estate_investments_user_id'), table_name='real_estate_investments')
    op.drop_table('real_estate_investments')
    op.drop_table('mining_subscriptions')
    op.drop_table('login_history')
    op.drop_table('documents')
    op.drop_index(op.f('ix_copy_trading_user_id'), table_name='copy_trading')
    op.drop_index(op.f('ix_copy_trading_bitget_copy_id'), table_name='copy_trading')
    op.drop_table('copy_trading')
    op.drop_index(op.f('ix_copied_signals_user_id'), table_name='copied_signals')
    op.drop_table('copied_signals')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_withdrawals_user_id'), table_name='withdrawals')
    op.drop_index(op.f('ix_withdrawals_id'), table_name='withdrawals')
    op.drop_index(op.f('ix_withdrawals_confirmation_token'), table_name='withdrawals')
    op.drop_table('withdrawals')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_assets_user_id'), table_name='user_assets')
    op.drop_index(op.f('ix_user_assets_id'), table_name='user_assets')
    op.drop_index(op.f('ix_user_assets_asset_symbol'), table_name='user_assets')
    op.drop_table('user_assets')
    op.drop_index(op.f('ix_trading_pairs_symbol'), table_name='trading_pairs')
    op.drop_index(op.f('ix_trading_pairs_id'), table_name='trading_pairs')
    op.drop_table('trading_pairs')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_support_tickets_user_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_id'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_support_messages_ticket_id'), table_name='support_messages')
    op.drop_index(op.f('ix_support_messages_id'), table_name='support_messages')
    op.drop_table('support_messages')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index(op.f('ix_signals_asset_type'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_signal_history_symbol'), table_name='signal_history')
    op.drop_index(op.f('ix_signal_history_signal_id'), table_name='signal_history')
    op.drop_table('signal_history')
    op.drop_index(op.f('ix_signal_generic_cache_expires_at'), table_name='signal_generic_cache')
    op.drop_index(op.f('ix_signal_generic_cache_cache_key'), table_name='signal_generic_cache')
    op.drop_table('signal_generic_cache')
    op.drop_index(op.f('ix_signal_accuracy_symbol'), table_name='signal_accuracy')
    op.drop_table('signal_accuracy')
    op.drop_table('real_estate_properties')
    op.drop_index(op.f('ix_real_estate_cache_cache_key'), table_name='real_estate_cache')
    op.drop_table('real_estate_cache')
    op.drop_index(op.f('ix_price_alerts_user_id'), table_name='price_alerts')
    op.drop_index(op.f('ix_price_alerts_id'), table_name='price_alerts')
    op.drop_table('price_alerts')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('mining_stats')
    op.drop_table('mining_plans')
    op.drop_index(op.f('ix_investment_products_id'), table_name='investment_products')
    op.drop_table('investment_products')
    op.drop_index(op.f('ix_investment_positions_user_id'), table_name='investment_positions')
    op.drop_index(op.f('ix_investment_positions_id'), table_name='investment_positions')
    op.drop_table('investment_positions')
    op.drop_index(op.f('ix_execution_trades_user_id'), table_name='execution_trades')
    op.drop_index(op.f('ix_execution_trades_order_id'), table_name='execution_trades')
    op.drop_index(op.f('ix_execution_trades_id'), table_name='execution_trades')
    op.drop_table('execution_trades')
    op.drop_index(op.f('ix_deposits_user_id'), table_name='deposits')
    op.drop_index(op.f('ix_deposits_id'), table_name='deposits')
    op.drop_table('deposits')
    op.drop_index(op.f('ix_deposit_addresses_network'), table_name='deposit_addresses')
    op.drop_index(op.f('ix_deposit_addresses_id'), table_name='deposit_addresses')
    op.drop_index(op.f('ix_deposit_addresses_asset'), table_name='deposit_addresses')
    op.drop_table('deposit_addresses')
    op.drop_index(op.f('ix_copy_traders_id'), table_name='copy_traders')
    op.drop_table('copy_traders')
    op.drop_index(op.f('ix_copy_sessions_user_id'), table_name='copy_sessions')
    op.drop_index(op.f('ix_copy_sessions_id'), table_name='copy_sessions')
    op.drop_table('copy_sessions')
    op.drop_index(op.f('ix_cold_storage_vaults_user_id'), table_name='cold_storage_vaults')
    op.drop_index(op.f('ix_cold_storage_vaults_id'), table_name='cold_storage_vaults')
    op.drop_table('cold_storage_vaults')
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
