"""Add Position model

Revision ID: 4f0ae272dfb6
Revises: d21d3da93523
Create Date: 2026-06-16 10:22:36.123812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f0ae272dfb6'
down_revision: Union[str, Sequence[str], None] = 'd21d3da93523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE positionstatus AS ENUM ('OPEN', 'CLOSED');")
    op.execute("""
    CREATE TABLE positions (
        id VARCHAR(36) NOT NULL,
        user_id VARCHAR(36) NOT NULL,
        symbol VARCHAR(20) NOT NULL,
        side orderside NOT NULL,
        quantity FLOAT NOT NULL,
        entry_price FLOAT NOT NULL,
        leverage FLOAT,
        margin FLOAT,
        take_profit FLOAT,
        stop_loss FLOAT,
        status positionstatus DEFAULT 'OPEN',
        realized_pnl FLOAT,
        created_at TIMESTAMP WITHOUT TIME ZONE,
        updated_at TIMESTAMP WITHOUT TIME ZONE,
        closed_at TIMESTAMP WITHOUT TIME ZONE,
        PRIMARY KEY (id)
    );
    """)
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_index(op.f('ix_positions_user_id'), 'positions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_positions_user_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_table('positions')
    # ### end Alembic commands ###
