"""Add copy trading models

Revision ID: 7535a4273f76
Revises: 3c24d93f3806
Create Date: 2026-03-17 11:46:44.498360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '7535a4273f76'
down_revision: Union[str, Sequence[str], None] = '3c24d93f3806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    bind = op.get_bind()
    insp = inspect(bind)
    
    # Check and add columns to transactions table
    trans_cols = [c['name'] for c in insp.get_columns('transactions')]
    if 'account_id' not in trans_cols:
        op.add_column('transactions', sa.Column('account_id', sa.String(length=36), nullable=True))
    
    # Check and add foreign keys to transactions table
    trans_fks = [fk['name'] for fk in insp.get_foreign_keys('transactions')]
    if 'fk_transactions_user_id_users' not in trans_fks:
        op.create_foreign_key('fk_transactions_user_id_users', 'transactions', 'users', ['user_id'], ['id'])
    if 'fk_transactions_account_id_accounts' not in trans_fks:
        op.create_foreign_key('fk_transactions_account_id_accounts', 'transactions', 'accounts', ['account_id'], ['id'])
    
    # Check and add column to users table
    user_cols = [c['name'] for c in insp.get_columns('users')]
    if 'email_verification_expires_at' not in user_cols:
        op.add_column('users', sa.Column('email_verification_expires_at', sa.DateTime(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verification_expires_at')
    op.drop_constraint('fk_transactions_account_id_accounts', 'transactions', type_='foreignkey')
    op.drop_constraint('fk_transactions_user_id_users', 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'account_id')
    # ### end Alembic commands ###
