"""Add unique constraint to mining_stats coin_symbol

Revision ID: a1b2c3d4e5f6
Revises: 7535a4273f76
Create Date: 2026-03-19 11:46:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = '7535a4273f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, remove any duplicate rows by keeping the most recent one for each coin_symbol
    op.execute("""
        DELETE FROM mining_stats 
        WHERE id NOT IN (
            SELECT max_id FROM (
                SELECT MAX(id) as max_id, coin_symbol 
                FROM mining_stats 
                GROUP BY coin_symbol
            ) AS grouped
        )
    """)
    
    # Add unique constraint on coin_symbol
    op.create_unique_constraint('uq_mining_stats_coin_symbol', 'mining_stats', ['coin_symbol'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_mining_stats_coin_symbol', 'mining_stats', type_='unique')
    # ### end Alembic commands ###
