"""add_compliance_fields

Revision ID: b6eb831b00ef
Revises: d63aa356b494
Create Date: 2026-05-01 23:02:31.929571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6eb831b00ef'
down_revision: Union[str, Sequence[str], None] = 'd63aa356b494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tax_residency', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('data_sharing_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'data_sharing_enabled')
    op.drop_column('users', 'tax_residency')
    # ### end Alembic commands ###
