"""Add proof_url to Deposit

Revision ID: bc1975910ee9
Revises: 26b06d33bdc1
Create Date: 2026-06-13 02:37:35.467075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc1975910ee9'
down_revision: Union[str, Sequence[str], None] = '26b06d33bdc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposits', sa.Column('proof_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deposits', 'proof_url')
    # ### end Alembic commands ###
