"""Add take profit to orders

Revision ID: c2519261247f
Revises: bc1975910ee9
Create Date: 2026-06-14 20:19:10.331593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2519261247f'
down_revision: Union[str, Sequence[str], None] = 'bc1975910ee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('take_profit', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'take_profit')
    # ### end Alembic commands ###
