"""add_cold_storage_vault_support

Revision ID: c41c8712965d
Revises: 04af1d8ef041
Create Date: 2026-04-06 11:33:07.105534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c41c8712965d'
down_revision: Union[str, Sequence[str], None] = '04af1d8ef041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop child table first (copy_trade_history has FK to copy_trading)
    op.drop_index(op.f('ix_copy_trade_history_copy_trading_id'), table_name='copy_trade_history')
    op.drop_table('copy_trade_history')
    # Then drop parent table
    op.drop_index(op.f('ix_copy_trading_bitget_copy_id'), table_name='copy_trading')
    op.drop_index(op.f('ix_copy_trading_user_id'), table_name='copy_trading')
    op.drop_table('copy_trading')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')
    op.create_foreign_key(None, 'copied_signals', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'copied_signals', type_='foreignkey')
    # Create parent table first (copy_trading)
    op.create_table('copy_trading',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('bitget_copy_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('bitget_trader_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('trader_username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('copy_mode', postgresql.ENUM('PROPORTIONAL', 'FIXED_AMOUNT', 'PERCENTAGE', name='copymodeenum'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'PAUSED', 'STOPPED', name='copystatus'), autoincrement=False, nullable=False),
    sa.Column('leverage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fixed_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_position_size', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('stop_loss_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('stop_loss_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('take_profit_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('take_profit_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_daily_copy_trades', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('auto_stop_on_loss', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('auto_stop_loss_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_copied_trades', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_pnl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_pnl_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('win_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('loss_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cumulative_loss', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('daily_trades_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('stopped_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('copy_trading_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('copy_trading_pkey'))
    )
    op.create_index(op.f('ix_copy_trading_user_id'), 'copy_trading', ['user_id'], unique=False)
    op.create_index(op.f('ix_copy_trading_bitget_copy_id'), 'copy_trading', ['bitget_copy_id'], unique=True)
    # Then create child table (copy_trade_history with FK to copy_trading)
    op.create_table('copy_trade_history',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('copy_trading_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('bitget_trade_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('side', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('entry_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('exit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pnl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pnl_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('opened_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('closed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['copy_trading_id'], ['copy_trading.id'], name=op.f('copy_trade_history_copy_trading_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('copy_trade_history_pkey')),
    sa.UniqueConstraint('bitget_trade_id', name=op.f('copy_trade_history_bitget_trade_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_copy_trade_history_copy_trading_id'), 'copy_trade_history', ['copy_trading_id'], unique=False)
    op.create_table('admins',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'DISABLED', name='adminstatus'), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('admins_pkey'))
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    # ### end Alembic commands ###
