"""add leverage and margin to orders

Revision ID: d21d3da93523
Revises: c2519261247f
Create Date: 2026-06-16 04:31:36.272414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd21d3da93523'
down_revision: Union[str, Sequence[str], None] = 'c2519261247f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('leverage', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('margin', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'margin')
    op.drop_column('orders', 'leverage')
    # ### end Alembic commands ###
