"""add_trading_preferences

Revision ID: d63aa356b494
Revises: 621a09757bce
Create Date: 2026-05-01 21:27:57.870052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd63aa356b494'
down_revision: Union[str, Sequence[str], None] = '621a09757bce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_order_type', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('default_lot_size', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('default_leverage', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('confirmation_dialogs', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('one_click_trading', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('slippage_tolerance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'slippage_tolerance')
    op.drop_column('users', 'one_click_trading')
    op.drop_column('users', 'confirmation_dialogs')
    op.drop_column('users', 'default_leverage')
    op.drop_column('users', 'default_lot_size')
    op.drop_column('users', 'default_order_type')
    # ### end Alembic commands ###
