"""Add mining stats and system settings tables

Revision ID: e227a0f0f4d2
Revises: 2bdc633888b3
Create Date: 2026-03-18 21:18:55.805813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e227a0f0f4d2'
down_revision: Union[str, Sequence[str], None] = '2bdc633888b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mining_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('coin_symbol', sa.String(length=20), nullable=False),
    sa.Column('network_hashrate', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('next_difficulty_est', sa.String(length=50), nullable=True),
    sa.Column('block_time_avg', sa.Float(), nullable=True),
    sa.Column('daily_revenue_per_hash', sa.Float(), nullable=True),
    sa.Column('active_miners_count', sa.Float(), nullable=True),
    sa.Column('total_platform_hashrate', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=1000), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    op.drop_table('mining_stats')
    # ### end Alembic commands ###
