"""add copy_trading_enabled to user

Revision ID: ea4b4aecf90c
Revises: b36236f7ec9e
Create Date: 2026-03-21 04:31:17.066783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea4b4aecf90c'
down_revision: Union[str, Sequence[str], None] = 'b36236f7ec9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('copy_trading_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'copy_trading_enabled')
    # ### end Alembic commands ###
