"""update_wallet_unique_constraints

Revision ID: fda9b6ff2178
Revises: add_subscription_plan_tier_enum
Create Date: 2026-04-27 00:06:36.119320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fda9b6ff2178'
down_revision: Union[str, Sequence[str], None] = 'add_subscription_plan_tier_enum'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_referral_payout_user_date', 'referral_payouts', ['referrer_id', 'payout_date'])
    op.drop_constraint(op.f('uq_referrals_referred_id'), 'referrals', type_='unique')
    op.drop_index(op.f('ix_referrals_referred_id'), table_name='referrals')
    op.create_index(op.f('ix_referrals_referred_id'), 'referrals', ['referred_id'], unique=True)
    op.create_foreign_key('fk_user_subscriptions_plan_id', 'user_subscriptions', 'subscription_plans', ['plan_id'], ['id'])
    
    # Handle address normalization
    op.add_column('wallets', sa.Column('address_normalized', sa.String(length=500), nullable=True))
    op.execute("UPDATE wallets SET address_normalized = LOWER(address)")
    op.alter_column('wallets', 'address_normalized', nullable=False)
    op.create_index(op.f('ix_wallets_address_normalized'), 'wallets', ['address_normalized'], unique=False)
    
    op.drop_constraint(op.f('wallets_address_key'), 'wallets', type_='unique')
    op.create_unique_constraint('uq_wallet_user_address_normalized', 'wallets', ['user_id', 'address_normalized'])
    
    # Update timestamps to be timezone-aware
    op.alter_column('wallets', 'created_at', type_=sa.DateTime(timezone=True), existing_type=sa.DateTime())
    op.alter_column('wallets', 'updated_at', type_=sa.DateTime(timezone=True), existing_type=sa.DateTime())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # This migration is one-way because the upgrade replaces a single-column unique constraint
    # on 'address' with a composite unique constraint on '(user_id, address)'.
    # A downgrade would require re-imposing the global unique constraint on 'address',
    # which will fail if multiple users have connected the same address.
    # Automatically resolving these conflicts would require deleting or modifying user data,
    # which is not safe to perform in an automated migration.
    raise NotImplementedError(
        "Downgrade is not supported for this migration because it allows duplicate "
        "wallet addresses across users, which violates the previous schema's constraints."
    )
