"""update_wallet_unique_constraints

Revision ID: fda9b6ff2178
Revises: add_subscription_plan_tier_enum
Create Date: 2026-04-27 00:06:36.119320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fda9b6ff2178'
down_revision: Union[str, Sequence[str], None] = 'add_subscription_plan_tier_enum'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_referral_payout_user_date', 'referral_payouts', ['referrer_id', 'payout_date'])
    op.drop_constraint(op.f('uq_referrals_referred_id'), 'referrals', type_='unique')
    op.drop_index(op.f('ix_referrals_referred_id'), table_name='referrals')
    op.create_index(op.f('ix_referrals_referred_id'), 'referrals', ['referred_id'], unique=True)
    op.create_foreign_key(None, 'user_subscriptions', 'subscription_plans', ['plan_id'], ['id'])
    op.drop_constraint(op.f('wallets_address_key'), 'wallets', type_='unique')
    op.create_unique_constraint('uq_wallet_user_address', 'wallets', ['user_id', 'address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_wallet_user_address', 'wallets', type_='unique')
    op.create_unique_constraint(op.f('wallets_address_key'), 'wallets', ['address'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'user_subscriptions', type_='foreignkey')
    op.drop_index(op.f('ix_referrals_referred_id'), table_name='referrals')
    op.create_index(op.f('ix_referrals_referred_id'), 'referrals', ['referred_id'], unique=False)
    op.create_unique_constraint(op.f('uq_referrals_referred_id'), 'referrals', ['referred_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_referral_payout_user_date', 'referral_payouts', type_='unique')
    # ### end Alembic commands ###
